name: Cosign Sign Container Test
on: [workflow_dispatch]
jobs:
  Cosign-Sign-Container-Test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install ca-certificates
        run: sudo apt-get update && sudo apt-get install ca-certificates -y
      - name: Add self signed sigstore cert
        run: sudo cp nginx-selfsigned.crt /usr/local/share/ca-certificates/nginx-selfsigned.crt && sudo update-ca-certificates
      - name: Install cosign
        uses: sigstore/cosign-installer@v3.0.2
        with:
         cosign-release: 'v2.0.1'
      - name: Check install!
        run: cosign version
      - name: Check docker install!
        run: command -v docker
      - name: Pull Rekor Public Key
        run: curl -k -o rekor.pub https://34.171.57.150/rekor/api/v1/log/publicKey
      - name: Pull Fulcio Root Cert
        run: curl -k -o fulcio.root.crt https://34.171.57.150/fulcio/api/v1/rootCert
      - name: print envs
        run: env
      - name: Setup Image
        run: |
          IMAGE_NAME=$(uuidgen) 
          IMAGE=ttl.sh/$IMAGE_NAME:5m
          cosign copy alpine $IMAGE
          echo "IMAGE=$IMAGE" >> "$GITHUB_ENV"
      - name: Setup Image URL
        run: |
          IMAGE_URL=`cat imageurl`
          echo $IMAGE_URL
      - name: Try get OIDC token
        env: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo $github_token
          echo ${{ vars.ECR_ACCOUNT }}
          echo ${{ secrets.ECR_PASSWORD }}
      - name: Test env and secrets
        env: 
          ecr_account: ${{ vars.ECR_ACCOUNT }}
          ecr_password: ${{ secrets.ECR_PASSWORD }}
        run: cosign login -u $ecr_account -p $ecr_password 987780704976.dkr.ecr.us-west-2.amazonaws.com
      - name: cosign login
        run: |
          cosign login -u AWS -p eyJwYXlsb2FkIjoiNmw2RDFGR3hmWVBlOWFYelRMTURhWWUwWlZBSU5jV3lhZEg1MHQ2ZmZDRFU2Ylg4VGhpUUkrVmJCM01hTERGRUFDeFp5aklrZkFZb2Fta21BY0E3czFieUQ3Um8zQXRoOWQrUHk3Q0R1c003NzU1Qll5V0hCTUJBanNjVHVGR1Y1RDJyUUpIY0ZlU2trbjZjTlJmdFRUZ0dMVlErczhTQUxJcG4rc3JXTG0vZ2hJU1F6NzJkZ21CM3dCWXp1eWt4OWg0Y1NpUHBpWEtDQ2xnYlVQcFk0a2txc1RIZTNpNzNxQUdLVHUyWXZIVWYvTXRuQ1lLYUxSNWVBUXdkUkdFaGxKWXA5L1V0blFRMTdpNEg5R1BaakthcExYRFV2SHB5SDVuVkg5M0FRdHJLRjdoY3BubHBTVEt6NUtDMU5KMVNzNVNNbTM3VHpVMDRBM3hpNmJneHd5RHBETzVVQVBHb1BBZ0V5a3NJc2JnSVpwa0ZrNHVGVWlyRi9vQnpBOG51aENBMmgrbytXWmhUS1ExL3JoeGtWTzM1QXFPUEZpcXJGSEdOYzlOaFZVdzBJY2JBUHlST0RHckh5R294QXZ1KzF6Z2dNUC9WK3lNUVlJTXN5bDJ5ZWtYdHdwQW1CZmVLV2NXbXd5alFSc0RCMjRQdjU5NHl5RG9kcDAyTkJRVWRoQmhXWloxdXFXdmFkMTdZSDFJV2JRdVMrRVg3S0xyVFM3eXVjV3NyTkRNU0FlRis0NDBHM1p6UmRNZWpsNXBSaVRDR1pwL1ZjQndMMXhiMkU2Wmo4eThsMWlDOVByUkJEcmxWOVlsdWZ6eGVaUXArbmEwU0hsR096VWxyMkFGZkVLaS9nOXlYMU5uWHFUUkZER0hGNkI0MkpNS1NJQWZmVEhERVgwenAxM2gzcDNBVXFpNllDUDE1UXVON0huWkFyNFA0U3UxZURpelJKbnpCZHovcFcwNTZMRFloSjBHNzJjVnFZTFd1VHRuMXpSRTRCWkh5ZVAzdEhCWmtoYTVyVHFRWE1QcExtQTE5QmRSdGJ3NUZWckVYTzRHT0lDU2NHWHFqdll2Q1RaeklFclhBbEQ2MWhiZ05uL2p4Rjd4RVExSTM3Wks0Ulg1Z0FxNkVJV1VYck90QWJoa08wS3ZsYmpMYmhQV24zcGh2R0RpZm8xZHZCMW5WME0vK3ozVDNqUlZuMWt3ZTNiOGEwQlg5N1k4bnRkd2tncWU4YzhwekRBTmNhYlJRWlV1RWFiQTJqNUpuMzBNZEorQmJqTmdINThQMDhmaEVQUWJKSXRqM0F3QzN2VzFzc2l5VnJkNDVqWHo2UGNhR3JaOGpmaTgxb1dxSUw1ZjA1b2pxbVNMMVlObENjL0lDdEo4eVNCVTZ5NFpaWkhoTGJwMVZtUHVjVXc9PSIsImRhdGFrZXkiOiJBUUVCQUhqNmxjNFhJSncvN2xuMEhjMDBETWVrNkdFeEhDYlk0UklwVE1DSTU4SW5Vd0FBQUg0d2ZBWUpLb1pJaHZjTkFRY0dvRzh3YlFJQkFEQm9CZ2txaGtpRzl3MEJCd0V3SGdZSllJWklBV1VEQkFFdU1CRUVEQmJQcnA0RDdHVnVWeFlyK0FJQkVJQTdmR1hLZmFZankvMy9UNm0wMDVzV2NEYkFxVzJMNCtLUm1kUWNQWGU2M2ZQM25ueEk0Um00cnVrRlNwTGtwakpQMUhjbDNaSWdIYXlwcFFjPSIsInZlcnNpb24iOiIyIiwidHlwZSI6IkRBVEFfS0VZIiwiZXhwaXJhdGlvbiI6MTY5OTQ3NzM5OH0= 987780704976.dkr.ecr.us-west-2.amazonaws.com
      - name: Sign Image
        env:
          SIGSTORE_REKOR_PUBLIC_KEY: "rekor.pub"
          SIGSTORE_ROOT_FILE: "fulcio.root.crt"
          SIGSTORE_CT_LOG_PUBLIC_KEY_FILE: "ct_pub.pem"
        run: cosign sign --rekor-url=https://34.171.57.150/rekor --fulcio-url=https://34.171.57.150/fulcio ${{ env.IMAGE }} -y
      - name: Verify Image
        env:
          SIGSTORE_REKOR_PUBLIC_KEY: "rekor.pub"
          SIGSTORE_ROOT_FILE: "fulcio.root.crt"
          SIGSTORE_CT_LOG_PUBLIC_KEY_FILE: "ct_pub.pem"
        run: cosign verify --rekor-url=https://34.171.57.150/rekor --certificate-identity https://github.com/${{ github.workflow_ref }} --certificate-oidc-issuer https://token.actions.githubusercontent.com ${{ env.IMAGE }}
      - name: Sign ECR Image
        env:
          SIGSTORE_REKOR_PUBLIC_KEY: "rekor.pub"
          SIGSTORE_ROOT_FILE: "fulcio.root.crt"
          SIGSTORE_CT_LOG_PUBLIC_KEY_FILE: "ct_pub.pem"
        run: |
          IMAGE_URL=`cat imageurl`
          cosign sign --rekor-url=https://34.171.57.150/rekor --fulcio-url=https://34.171.57.150/fulcio $IMAGE_URL -y
      - name: Verify ECR Image
        env:
          SIGSTORE_REKOR_PUBLIC_KEY: "rekor.pub"
          SIGSTORE_ROOT_FILE: "fulcio.root.crt"
          SIGSTORE_CT_LOG_PUBLIC_KEY_FILE: "ct_pub.pem"
        run: | 
          IMAGE_URL=`cat imageurl`
          cosign verify --rekor-url=https://34.171.57.150/rekor --certificate-identity https://github.com/${{ github.workflow_ref }} --certificate-oidc-issuer https://token.actions.githubusercontent.com $IMAGE_URL
