name: Cosign Sign Container Test
on: [workflow_dispatch]
jobs:
  Cosign-Sign-Container-Test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install ca-certificates
        run: sudo apt-get update && sudo apt-get install ca-certificates -y
      - name: Add self signed sigstore cert
        run: sudo cp nginx-selfsigned.crt /usr/local/share/ca-certificates/nginx-selfsigned.crt && sudo update-ca-certificates
      - name: Install cosign
        uses: sigstore/cosign-installer@v3.0.2
        with:
         cosign-release: 'v2.0.1'
      - name: Check install!
        run: cosign version
      - name: Pull Rekor Public Key
        run: curl -k -o rekor.pub https://34.171.57.150/rekor/api/v1/log/publicKey
      - name: Pull Fulcio Root Cert
        run: curl -k -o fulcio.root.crt https://34.171.57.150/fulcio/api/v1/rootCert
      - name: Setup Image
        run: |
          IMAGE_NAME=$(uuidgen) 
          IMAGE=ttl.sh/$IMAGE_NAME:5m
          cosign copy alpine $IMAGE
          echo "IMAGE=$IMAGE" >> "$GITHUB_ENV"
      - name: Setup Image URL
        run: |
          IMAGE_URL=`cat imageurl`
          echo $IMAGE_URL
          ls -l
      - name: Try get OIDC token
        run: |
          echo $SIGSTORE_ID_TOKEN
          echo $ACTIONS_ID_TOKEN_REQUEST_URL
          echo $ACTIONS_ID_TOKEN_REQUEST_TOKEN
      - name: cosign login
        run: |
        echo ${{ vars.ECR_ACCOUNT }}
        cosign login -u AWS -p eyJwYXlsb2FkIjoiUUFlRTMxVURUQmlUd3ozM1kybXd2Tksrc0JwYU4wZTV0UDQwOFY1WTdLeTFtZ2JDR0Vad1RJUmR5RDVjSG40aERuVW5ROHg3RFFFakZNaEJNamZuSjNOY1MyVzhuRnFPM3JQelVZRXRNRzFxS1Fsb3pQL3pIc292bHZQVWcyR0IzRjBLdm9BRWVLK016L3pteVBtQ1RGWHFaQVdPVkRqVm81UjZOMXNRK1RLbG5salh2bzR0U3VncU51dDlZTmU4eVlyMWRlM0hDL3JzbGlpeUZubWdJMFM3YTh0a0gvYzZKM2VLS0hXeVBWWG1xUUdJeWlXUHdQQlRsRWsxOVZRbk1ZRnhNcVNWRzBKeG5LYXNlWjNCUWpJSEw5SzI0N1A3ZUlYUE9VME5LcUNYZVdPYkErMmV2cTBOM1FlVjJIK21qODl3MDVFSTRTS01GdnF6K0huYUtLSndQWHVzRk1Tb3pQaThBVW5hV0JxSFQ2Z0tjV29FQ2tzY0gvbFZUL3pPRFJUMDV4YlBOcHg4eVlFdFBWaWw0bVBNQStCb2k2UzVDRHdyMXkrN3NEWEhZZm8reFJ5WlN2cStSZTZsalEwNHo2d2RVWVdmcjk5QW1UZ1BaRnljalk4TE9JRUFmTU8vRytIeVNKYndtMzBuVXM0Q2N1MnBIR3RSdWhtSU1HYzhpMENKdk5uZUpOZm1USXZBampKNGlmRzhGWUxPcUhXWjREcjBMUG1vOXBGbGx2dkNrY3RpM0tFd1dCSkNNWnJ2dC9saUZMT1dvWkRYQlIwV1BKMFc2c2p4QlhDZ2gycjg1eGRsTlhsaUNtaVl5eHAxaGlTU21VRUNSK3dtdUxod01pdHQvUkFXRVdsUlEySU5UeDVKSzhpT1BiTE1pUmVsMUZLbkx1V3dSZXM0ekdKd29GMmVBd2U1cGVVYkN2aS9zbjZhQTdmckRzTHFBUHU3Znorazc4M2VpZWRnS0w5ZVJ6ejVCZEpDa1NVdCs2RmZiVHBxeUtudXV4U3U1WThJbGVWQS9ibjcrdXQ4ejdBb2lxcUdwdDM3SXZiRm92QkJ6djNEdkZNMmNEd013TmlyZ05DcytGY1kzMkFtTDVPaHlGRlB4OGMySUhKTFhDcjRXeFZ4dXN5UGxWdWZ6NDAxTm9QMUx5Z2tpWngvMUhPUFdGeFVXWlEwa0c2NTMzQ3UrMnJDd3RiQThFVzI3MGF6ekJlUHlqdFE5ZzMycTBudHlzb21GZVFyRXd3dDc2eTZJcHJ4UzJiejNZSkR2NTFORVFkMnpTVThIUkJiNXpnaDBSbFFNT1VhdTBUdVd2dGlHVHltd1VDbjMwdzJtOEJPVll2VWlRend4Q1dRZG45ak5HdUhML3ovWHlQQmhBWlpuQT09IiwiZGF0YWtleSI6IkFRRUJBSGo2bGM0WElKdy83bG4wSGMwMERNZWs2R0V4SENiWTRSSXBUTUNJNThJblV3QUFBSDR3ZkFZSktvWklodmNOQVFjR29HOHdiUUlCQURCb0Jna3Foa2lHOXcwQkJ3RXdIZ1lKWUlaSUFXVURCQUV1TUJFRURLMm1PRkJoN2hGU3hma3B5UUlCRUlBN1dmb2I1V1VXMlg2TFAvMnBiOXNuekFKZ1ZFZFVsUjJoQktCbVdXbThUMGdqdlB5dysyM1ozQVdqM1ora1hqSU8rSTZZU1UyNlJ6RTJhRVk9IiwidmVyc2lvbiI6IjIiLCJ0eXBlIjoiREFUQV9LRVkiLCJleHBpcmF0aW9uIjoxNjk3MjIxMzkxfQ== 987780704976.dkr.ecr.us-west-2.amazonaws.com
      - name: Sign Image
        env:
          SIGSTORE_REKOR_PUBLIC_KEY: "rekor.pub"
          SIGSTORE_ROOT_FILE: "fulcio.root.crt"
          SIGSTORE_CT_LOG_PUBLIC_KEY_FILE: "ct_pub.pem"
        run: cosign sign --rekor-url=https://34.171.57.150/rekor --fulcio-url=https://34.171.57.150/fulcio ${{ env.IMAGE }} -y
      - name: Verify Image
        env:
          SIGSTORE_REKOR_PUBLIC_KEY: "rekor.pub"
          SIGSTORE_ROOT_FILE: "fulcio.root.crt"
          SIGSTORE_CT_LOG_PUBLIC_KEY_FILE: "ct_pub.pem"
        run: cosign verify --rekor-url=https://34.171.57.150/rekor --certificate-identity https://github.com/${{ github.workflow_ref }} --certificate-oidc-issuer https://token.actions.githubusercontent.com ${{ env.IMAGE }}
      - name: Sign ECR Image
        env:
          SIGSTORE_REKOR_PUBLIC_KEY: "rekor.pub"
          SIGSTORE_ROOT_FILE: "fulcio.root.crt"
          SIGSTORE_CT_LOG_PUBLIC_KEY_FILE: "ct_pub.pem"
        run: cosign sign --rekor-url=https://34.171.57.150/rekor --fulcio-url=https://34.171.57.150/fulcio 987780704976.dkr.ecr.us-west-2.amazonaws.com/arubaos/container-manager:1.2.0-alpha.1-arm -y
      - name: Verify ECR Image
        env:
          SIGSTORE_REKOR_PUBLIC_KEY: "rekor.pub"
          SIGSTORE_ROOT_FILE: "fulcio.root.crt"
          SIGSTORE_CT_LOG_PUBLIC_KEY_FILE: "ct_pub.pem"
        run: cosign verify --rekor-url=https://34.171.57.150/rekor --certificate-identity https://github.com/${{ github.workflow_ref }} --certificate-oidc-issuer https://token.actions.githubusercontent.com 987780704976.dkr.ecr.us-west-2.amazonaws.com/arubaos/container-manager:1.2.0-alpha.1-arm64
